from __future__ import annotations

import pandas as pd

FEATURE_COLUMNS = [
    "model_name",
    "context_window_tokens",
    "max_output_tokens",
    "vocab_size",
    "positional_encoding_type",
    "attention_type",
    "tokenizer_type",
    "is_open_source",
    "knowledge_cutoff_year",
    "multilingual_support",
    "temperature",
    "top_p",
    "top_k",
    "repetition_penalty",
    "frequency_penalty",
    "presence_penalty",
    "max_tokens_requested",
    "stop_sequences_count",
    "galileo_qa_no_rag",
    "galileo_qa_with_rag",
    "galileo_longform",
    "crag_hallucination_rate",
    "crag_accuracy",
]


def _spec(
    model_name: str,
    *,
    context_window_tokens: int,
    max_output_tokens: int,
    vocab_size: int,
    positional_encoding_type: str,
    attention_type: str,
    tokenizer_type: str,
    is_open_source: bool,
    knowledge_cutoff_year: int,
    multilingual_support: bool,
    temperature: float,
    top_p: float,
    galileo_qa_no_rag: float,
    galileo_qa_with_rag: float,
    galileo_longform: float,
    crag_hallucination_rate: float,
    crag_accuracy: float,
    top_k: float | None = None,
    repetition_penalty: float | None = None,
    frequency_penalty: float | None = None,
    presence_penalty: float | None = None,
    max_tokens_requested: int = 4096,
    stop_sequences_count: int = 0,
) -> dict:
    return {
        "model_name": model_name,
        "context_window_tokens": context_window_tokens,
        "max_output_tokens": max_output_tokens,
        "vocab_size": vocab_size,
        "positional_encoding_type": positional_encoding_type,
        "attention_type": attention_type,
        "tokenizer_type": tokenizer_type,
        "is_open_source": is_open_source,
        "knowledge_cutoff_year": knowledge_cutoff_year,
        "multilingual_support": multilingual_support,
        "temperature": temperature,
        "top_p": top_p,
        "top_k": top_k,
        "repetition_penalty": repetition_penalty,
        "frequency_penalty": frequency_penalty,
        "presence_penalty": presence_penalty,
        "max_tokens_requested": max_tokens_requested,
        "stop_sequences_count": stop_sequences_count,
        "galileo_qa_no_rag": galileo_qa_no_rag,
        "galileo_qa_with_rag": galileo_qa_with_rag,
        "galileo_longform": galileo_longform,
        "crag_hallucination_rate": crag_hallucination_rate,
        "crag_accuracy": crag_accuracy,
    }


def _open_llama2(model_name: str, attention_type: str, galileo: float, crag_h: float, crag_a: float) -> dict:
    return _spec(
        model_name,
        context_window_tokens=4096,
        max_output_tokens=2048,
        vocab_size=32000,
        positional_encoding_type="RoPE",
        attention_type=attention_type,
        tokenizer_type="sentencepiece_BPE",
        is_open_source=True,
        knowledge_cutoff_year=2023,
        multilingual_support=False,
        temperature=0.6,
        top_p=0.9,
        top_k=50,
        repetition_penalty=1.1,
        max_tokens_requested=2048,
        stop_sequences_count=1,
        galileo_qa_no_rag=galileo,
        galileo_qa_with_rag=round(galileo + 0.03, 3),
        galileo_longform=round(galileo + 0.15, 3),
        crag_hallucination_rate=crag_h,
        crag_accuracy=crag_a,
    )


def _open_llama3(model_name: str, context_window_tokens: int, galileo: float, crag_h: float, crag_a: float) -> dict:
    return _spec(
        model_name,
        context_window_tokens=context_window_tokens,
        max_output_tokens=4096,
        vocab_size=128256,
        positional_encoding_type="RoPE",
        attention_type="GQA",
        tokenizer_type="sentencepiece_BPE",
        is_open_source=True,
        knowledge_cutoff_year=2023,
        multilingual_support=True,
        temperature=0.6,
        top_p=0.9,
        top_k=50,
        repetition_penalty=1.1,
        max_tokens_requested=4096,
        stop_sequences_count=1,
        galileo_qa_no_rag=galileo,
        galileo_qa_with_rag=round(galileo + 0.02, 3),
        galileo_longform=round(galileo + 0.12, 3),
        crag_hallucination_rate=crag_h,
        crag_accuracy=crag_a,
    )


def _open_mistral7(model_name: str, context_window_tokens: int, galileo: float, crag_h: float, crag_a: float) -> dict:
    return _spec(
        model_name,
        context_window_tokens=context_window_tokens,
        max_output_tokens=4096,
        vocab_size=32000,
        positional_encoding_type="RoPE",
        attention_type="GQA",
        tokenizer_type="sentencepiece_BPE",
        is_open_source=True,
        knowledge_cutoff_year=2023,
        multilingual_support=True,
        temperature=0.7,
        top_p=0.9,
        top_k=50,
        repetition_penalty=1.05,
        max_tokens_requested=4096,
        stop_sequences_count=0,
        galileo_qa_no_rag=galileo,
        galileo_qa_with_rag=round(galileo + 0.03, 3),
        galileo_longform=round(galileo + 0.10, 3),
        crag_hallucination_rate=crag_h,
        crag_accuracy=crag_a,
    )


def _open_qwen15(model_name: str, galileo: float, crag_h: float, crag_a: float) -> dict:
    return _spec(
        model_name,
        context_window_tokens=32768,
        max_output_tokens=8192,
        vocab_size=151936,
        positional_encoding_type="RoPE",
        attention_type="GQA",
        tokenizer_type="bytelevel_BPE",
        is_open_source=True,
        knowledge_cutoff_year=2024,
        multilingual_support=True,
        temperature=0.7,
        top_p=0.8,
        top_k=20,
        repetition_penalty=1.05,
        max_tokens_requested=8192,
        stop_sequences_count=0,
        galileo_qa_no_rag=galileo,
        galileo_qa_with_rag=round(galileo + 0.02, 3),
        galileo_longform=round(galileo + 0.10, 3),
        crag_hallucination_rate=crag_h,
        crag_accuracy=crag_a,
    )


def _open_yi(model_name: str, galileo: float, crag_h: float, crag_a: float) -> dict:
    return _spec(
        model_name,
        context_window_tokens=4096,
        max_output_tokens=4096,
        vocab_size=64000,
        positional_encoding_type="RoPE",
        attention_type="GQA",
        tokenizer_type="sentencepiece_BPE",
        is_open_source=True,
        knowledge_cutoff_year=2023,
        multilingual_support=True,
        temperature=0.6,
        top_p=0.9,
        top_k=40,
        repetition_penalty=1.1,
        max_tokens_requested=4096,
        stop_sequences_count=0,
        galileo_qa_no_rag=galileo,
        galileo_qa_with_rag=round(galileo + 0.03, 3),
        galileo_longform=round(galileo + 0.11, 3),
        crag_hallucination_rate=crag_h,
        crag_accuracy=crag_a,
    )


def _closed_api(
    model_name: str,
    *,
    context_window_tokens: int,
    knowledge_cutoff_year: int,
    galileo: float,
    crag_h: float,
    crag_a: float,
    multilingual_support: bool = True,
    max_output_tokens: int = 4096,
) -> dict:
    return _spec(
        model_name,
        context_window_tokens=context_window_tokens,
        max_output_tokens=max_output_tokens,
        vocab_size=100277,
        positional_encoding_type="learned_absolute",
        attention_type="MHA",
        tokenizer_type="cl100k_BPE",
        is_open_source=False,
        knowledge_cutoff_year=knowledge_cutoff_year,
        multilingual_support=multilingual_support,
        temperature=1.0,
        top_p=1.0,
        frequency_penalty=0.0,
        presence_penalty=0.0,
        max_tokens_requested=max_output_tokens,
        stop_sequences_count=0,
        galileo_qa_no_rag=galileo,
        galileo_qa_with_rag=round(galileo - 0.01, 3),
        galileo_longform=round(galileo + 0.06, 3),
        crag_hallucination_rate=crag_h,
        crag_accuracy=crag_a,
    )


MODEL_FEATURES: dict[str, dict] = {
    "gpt-4-0613": _closed_api(
        "gpt-4-0613",
        context_window_tokens=8192,
        knowledge_cutoff_year=2021,
        galileo=0.77,
        crag_h=0.135,
        crag_a=0.335,
        max_output_tokens=4096,
    ),
    "meta-llama/Llama-2-70b-chat-hf": _open_llama2(
        "llama-2-70b-chat-hf", "GQA", 0.65, 0.287, 0.223
    ),
    "DeepSeek-Coder-V2": _spec(
        "DeepSeek-Coder-V2",
        context_window_tokens=131072,
        max_output_tokens=8192,
        vocab_size=102400,
        positional_encoding_type="RoPE",
        attention_type="MoE",
        tokenizer_type="bytelevel_BPE",
        is_open_source=True,
        knowledge_cutoff_year=2024,
        multilingual_support=True,
        temperature=0.6,
        top_p=0.95,
        top_k=50,
        repetition_penalty=1.05,
        max_tokens_requested=8192,
        stop_sequences_count=0,
        galileo_qa_no_rag=0.74,
        galileo_qa_with_rag=0.76,
        galileo_longform=0.84,
        crag_hallucination_rate=0.18,
        crag_accuracy=0.31,
    ),
    "Llama-2-7b-hf": _open_llama2("Llama-2-7b-hf", "MHA", 0.52, 0.39, 0.16),
    "Llama-2-13b-hf": _open_llama2("Llama-2-13b-hf", "MHA", 0.58, 0.34, 0.19),
    "Llama-2-70b-hf": _open_llama2("Llama-2-70b-hf", "GQA", 0.64, 0.29, 0.22),
    "Meta-Llama-3-8B": _open_llama3("Meta-Llama-3-8B", 8192, 0.60, 0.31, 0.20),
    "Meta-Llama-3-8B-Instruct": _open_llama3("Meta-Llama-3-8B-Instruct", 8192, 0.63, 0.28, 0.22),
    "Meta-Llama-3-70B": _open_llama3("Meta-Llama-3-70B", 8192, 0.71, 0.24, 0.27),
    "Meta-Llama-3-70B-Instruct": _open_llama3("Meta-Llama-3-70B-Instruct", 8192, 0.73, 0.22, 0.29),
    "Meta-Llama-3_1-8B": _open_llama3("Meta-Llama-3_1-8B", 131072, 0.62, 0.29, 0.21),
    "Meta-Llama-3_1-8B-Instruct": _open_llama3("Meta-Llama-3_1-8B-Instruct", 131072, 0.65, 0.26, 0.24),
    "Meta-Llama-3_1-70B": _open_llama3("Meta-Llama-3_1-70B", 131072, 0.72, 0.23, 0.28),
    "Meta-Llama-3_1-70B-Instruct": _open_llama3("Meta-Llama-3_1-70B-Instruct", 131072, 0.75, 0.20, 0.31),
    "Mistral-7B-v0.1": _open_mistral7("Mistral-7B-v0.1", 8192, 0.57, 0.33, 0.19),
    "Mistral-7B-v0.2-hf": _open_mistral7("Mistral-7B-v0.2-hf", 32768, 0.59, 0.31, 0.20),
    "Mistral-7B-Instruct-v0.1": _open_mistral7("Mistral-7B-Instruct-v0.1", 8192, 0.60, 0.30, 0.21),
    "Mistral-7B-Instruct-v0.2": _open_mistral7("Mistral-7B-Instruct-v0.2", 32768, 0.62, 0.28, 0.22),
    "Mixtral-8x7B-v0.1": _spec(
        "Mixtral-8x7B-v0.1",
        context_window_tokens=32768,
        max_output_tokens=4096,
        vocab_size=32000,
        positional_encoding_type="RoPE",
        attention_type="MoE",
        tokenizer_type="sentencepiece_BPE",
        is_open_source=True,
        knowledge_cutoff_year=2023,
        multilingual_support=True,
        temperature=0.7,
        top_p=0.9,
        top_k=50,
        repetition_penalty=1.05,
        max_tokens_requested=4096,
        stop_sequences_count=0,
        galileo_qa_no_rag=0.68,
        galileo_qa_with_rag=0.71,
        galileo_longform=0.80,
        crag_hallucination_rate=0.25,
        crag_accuracy=0.25,
    ),
    "Mixtral-8x7B-Instruct-v0.1": _spec(
        "Mixtral-8x7B-Instruct-v0.1",
        context_window_tokens=32768,
        max_output_tokens=4096,
        vocab_size=32000,
        positional_encoding_type="RoPE",
        attention_type="MoE",
        tokenizer_type="sentencepiece_BPE",
        is_open_source=True,
        knowledge_cutoff_year=2023,
        multilingual_support=True,
        temperature=0.7,
        top_p=0.9,
        top_k=50,
        repetition_penalty=1.05,
        max_tokens_requested=4096,
        stop_sequences_count=0,
        galileo_qa_no_rag=0.70,
        galileo_qa_with_rag=0.72,
        galileo_longform=0.81,
        crag_hallucination_rate=0.23,
        crag_accuracy=0.27,
    ),
    "Phi-3-mini-4k-instruct": _spec(
        "Phi-3-mini-4k-instruct",
        context_window_tokens=4096,
        max_output_tokens=4096,
        vocab_size=32064,
        positional_encoding_type="RoPE",
        attention_type="GQA",
        tokenizer_type="cl100k_BPE",
        is_open_source=True,
        knowledge_cutoff_year=2023,
        multilingual_support=True,
        temperature=0.7,
        top_p=0.9,
        top_k=50,
        repetition_penalty=1.05,
        max_tokens_requested=4096,
        stop_sequences_count=0,
        galileo_qa_no_rag=0.61,
        galileo_qa_with_rag=0.63,
        galileo_longform=0.76,
        crag_hallucination_rate=0.30,
        crag_accuracy=0.21,
    ),
    "Qwen1.5-7B-Chat": _open_qwen15("Qwen1.5-7B-Chat", 0.62, 0.30, 0.21),
    "Qwen1.5-14B-Chat": _open_qwen15("Qwen1.5-14B-Chat", 0.67, 0.27, 0.24),
    "Qwen1.5-72B-Chat": _open_qwen15("Qwen1.5-72B-Chat", 0.72, 0.24, 0.28),
    "Qwen1.5-110B": _open_qwen15("Qwen1.5-110B", 0.74, 0.22, 0.30),
    "Yi-6B": _open_yi("Yi-6B", 0.55, 0.35, 0.18),
    "Yi-6b-Chat": _open_yi("Yi-6b-Chat", 0.57, 0.33, 0.19),
    "Yi-34B": _open_yi("Yi-34B", 0.69, 0.26, 0.25),
    "arx_0314": _closed_api(
        "arx_0314",
        context_window_tokens=131072,
        knowledge_cutoff_year=2024,
        galileo=0.82,
        crag_h=0.12,
        crag_a=0.36,
        max_output_tokens=8192,
    ),
    "arx_3": _closed_api(
        "arx_3",
        context_window_tokens=131072,
        knowledge_cutoff_year=2024,
        galileo=0.79,
        crag_h=0.14,
        crag_a=0.34,
        max_output_tokens=8192,
    ),
    "c4ai-command-r-v01": _spec(
        "c4ai-command-r-v01",
        context_window_tokens=131072,
        max_output_tokens=4096,
        vocab_size=256000,
        positional_encoding_type="RoPE",
        attention_type="GQA",
        tokenizer_type="bytelevel_BPE",
        is_open_source=True,
        knowledge_cutoff_year=2024,
        multilingual_support=True,
        temperature=0.3,
        top_p=0.9,
        top_k=50,
        repetition_penalty=1.05,
        max_tokens_requested=4096,
        stop_sequences_count=0,
        galileo_qa_no_rag=0.66,
        galileo_qa_with_rag=0.69,
        galileo_longform=0.79,
        crag_hallucination_rate=0.27,
        crag_accuracy=0.24,
    ),
    "claude-3-5-haiku-20241022": _closed_api(
        "claude-3-5-haiku-20241022",
        context_window_tokens=200000,
        knowledge_cutoff_year=2024,
        galileo=0.74,
        crag_h=0.16,
        crag_a=0.32,
        max_output_tokens=8192,
    ),
    "claude-3-5-sonnet-20241022": _closed_api(
        "claude-3-5-sonnet-20241022",
        context_window_tokens=200000,
        knowledge_cutoff_year=2024,
        galileo=0.81,
        crag_h=0.13,
        crag_a=0.35,
        max_output_tokens=8192,
    ),
    "claude-3.5-sonnet": _closed_api(
        "claude-3.5-sonnet",
        context_window_tokens=200000,
        knowledge_cutoff_year=2024,
        galileo=0.80,
        crag_h=0.14,
        crag_a=0.34,
        max_output_tokens=8192,
    ),
    "deepseek": _spec(
        "deepseek",
        context_window_tokens=65536,
        max_output_tokens=8192,
        vocab_size=102400,
        positional_encoding_type="RoPE",
        attention_type="MoE",
        tokenizer_type="bytelevel_BPE",
        is_open_source=True,
        knowledge_cutoff_year=2024,
        multilingual_support=True,
        temperature=0.6,
        top_p=0.95,
        top_k=50,
        repetition_penalty=1.05,
        max_tokens_requested=8192,
        stop_sequences_count=0,
        galileo_qa_no_rag=0.70,
        galileo_qa_with_rag=0.72,
        galileo_longform=0.82,
        crag_hallucination_rate=0.22,
        crag_accuracy=0.28,
    ),
    "deepseek-chat-v2_5": _spec(
        "deepseek-chat-v2_5",
        context_window_tokens=131072,
        max_output_tokens=8192,
        vocab_size=102400,
        positional_encoding_type="RoPE",
        attention_type="MoE",
        tokenizer_type="bytelevel_BPE",
        is_open_source=True,
        knowledge_cutoff_year=2024,
        multilingual_support=True,
        temperature=0.6,
        top_p=0.95,
        top_k=50,
        repetition_penalty=1.05,
        max_tokens_requested=8192,
        stop_sequences_count=0,
        galileo_qa_no_rag=0.76,
        galileo_qa_with_rag=0.78,
        galileo_longform=0.85,
        crag_hallucination_rate=0.17,
        crag_accuracy=0.32,
    ),
    "flash_0shots_00_35_03": _closed_api(
        "flash_0shots_00_35_03",
        context_window_tokens=1048576,
        knowledge_cutoff_year=2024,
        galileo=0.72,
        crag_h=0.18,
        crag_a=0.30,
        max_output_tokens=8192,
    ),
    "gemini-1.5-flash-002": _closed_api(
        "gemini-1.5-flash-002",
        context_window_tokens=1048576,
        knowledge_cutoff_year=2024,
        galileo=0.73,
        crag_h=0.17,
        crag_a=0.31,
        max_output_tokens=8192,
    ),
    "gemini-1.5-pro-002": _closed_api(
        "gemini-1.5-pro-002",
        context_window_tokens=2097152,
        knowledge_cutoff_year=2024,
        galileo=0.78,
        crag_h=0.14,
        crag_a=0.34,
        max_output_tokens=8192,
    ),
    "gemma-7b": _spec(
        "gemma-7b",
        context_window_tokens=8192,
        max_output_tokens=4096,
        vocab_size=256000,
        positional_encoding_type="RoPE",
        attention_type="MHA",
        tokenizer_type="sentencepiece_BPE",
        is_open_source=True,
        knowledge_cutoff_year=2024,
        multilingual_support=True,
        temperature=0.7,
        top_p=0.9,
        top_k=50,
        repetition_penalty=1.05,
        max_tokens_requested=4096,
        stop_sequences_count=0,
        galileo_qa_no_rag=0.58,
        galileo_qa_with_rag=0.60,
        galileo_longform=0.74,
        crag_hallucination_rate=0.32,
        crag_accuracy=0.20,
    ),
    "gpt-4o-2024-08-06": _closed_api(
        "gpt-4o-2024-08-06",
        context_window_tokens=128000,
        knowledge_cutoff_year=2023,
        galileo=0.79,
        crag_h=0.13,
        crag_a=0.34,
        max_output_tokens=16384,
    ),
    "gpt-4o-mini": _closed_api(
        "gpt-4o-mini",
        context_window_tokens=128000,
        knowledge_cutoff_year=2023,
        galileo=0.71,
        crag_h=0.19,
        crag_a=0.29,
        max_output_tokens=16384,
    ),
    "gpt4o(2024-05-13)": _closed_api(
        "gpt4o(2024-05-13)",
        context_window_tokens=128000,
        knowledge_cutoff_year=2023,
        galileo=0.78,
        crag_h=0.14,
        crag_a=0.33,
        max_output_tokens=4096,
    ),
    "iask_pro": _closed_api(
        "iask_pro",
        context_window_tokens=131072,
        knowledge_cutoff_year=2024,
        galileo=0.80,
        crag_h=0.13,
        crag_a=0.35,
        max_output_tokens=8192,
    ),
    "jamba-1.5-large": _spec(
        "jamba-1.5-large",
        context_window_tokens=262144,
        max_output_tokens=4096,
        vocab_size=65536,
        positional_encoding_type="RoPE",
        attention_type="hybrid_Mamba",
        tokenizer_type="bytelevel_BPE",
        is_open_source=True,
        knowledge_cutoff_year=2024,
        multilingual_support=True,
        temperature=0.7,
        top_p=0.9,
        top_k=50,
        repetition_penalty=1.05,
        max_tokens_requested=4096,
        stop_sequences_count=0,
        galileo_qa_no_rag=0.68,
        galileo_qa_with_rag=0.70,
        galileo_longform=0.79,
        crag_hallucination_rate=0.26,
        crag_accuracy=0.25,
    ),
    "mathstral-7B": _open_mistral7("mathstral-7B", 32768, 0.64, 0.28, 0.23),
    "opus_2shots_00_37_14": _closed_api(
        "opus_2shots_00_37_14",
        context_window_tokens=200000,
        knowledge_cutoff_year=2024,
        galileo=0.83,
        crag_h=0.11,
        crag_a=0.37,
        max_output_tokens=8192,
    ),
    "sonnet-3.5_0shots_09_34_29": _closed_api(
        "sonnet-3.5_0shots_09_34_29",
        context_window_tokens=200000,
        knowledge_cutoff_year=2024,
        galileo=0.80,
        crag_h=0.14,
        crag_a=0.34,
        max_output_tokens=8192,
    ),
    "sonnet_0shots_12_01_18": _closed_api(
        "sonnet_0shots_12_01_18",
        context_window_tokens=200000,
        knowledge_cutoff_year=2023,
        galileo=0.76,
        crag_h=0.16,
        crag_a=0.31,
        max_output_tokens=4096,
    ),
}


def enrich_model_features(df: pd.DataFrame) -> pd.DataFrame:
    if "llm_model" not in df.columns:
        raise ValueError("Expected llm_model column")

    missing = sorted(set(df["llm_model"].unique()) - set(MODEL_FEATURES))
    if missing:
        raise KeyError(f"Missing model feature specs for: {missing}")

    feature_df = df["llm_model"].map(MODEL_FEATURES).apply(pd.Series)
    return pd.concat([df.reset_index(drop=True), feature_df[FEATURE_COLUMNS]], axis=1)
